=== DeeperBlue01/DeeperBlue01.github.io/cv_fr.dtd
<!ELEMENT cv (personal-info, education, experience, languages?, interests?, soft-skills?, technical-skills?)>
<!ELEMENT personal-info (name, address?, email, phone)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT education (school+)>
<!ELEMENT school (name, degree, year)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT degree (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT experience (job+)>
<!ELEMENT job (title, company, years, location?, contract?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT years (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT contract (#PCDATA)>
<!ELEMENT languages (language+)>
<!ELEMENT language (name, proficiency)>
<!ELEMENT proficiency (#PCDATA)>
<!ELEMENT interests (interest+)>
<!ELEMENT interest (#PCDATA)>
<!ELEMENT soft-skills (skill+)>
<!ELEMENT skill (#PCDATA)>
<!ELEMENT technical-skills (skill-category+)>
<!ELEMENT skill-category (name, skills)>
<!ELEMENT skills (skill+)>
<!ELEMENT skill (#PCDATA)>

=== DeeperBlue01/DeeperBlue01.github.io/cv_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv_fr.dtd">
<cv>
    <personal-info>
        <name>Jean Dupont</name>
        <email>jean.dupont@example.com</email>
        <phone>+33 6 12 34 56 78</phone>
    </personal-info>
    <education>
        <school>
            <name>Université Paris-Sorbonne</name>
            <degree>Master en Informatique</degree>
            <year>2020</year>
        </school>
    </education>
    <experience>
        <job>
            <title>Développeur Web</title>
            <company>Exemple SA</company>
            <years>2020-2023</years>
        </job>
    </experience>
    <languages>
        <language>
            <name>Français</name>
            <proficiency>Bilingue ou natal</proficiency>
        </language>
        <language>
            <name>Anglais</name>
            <proficiency>Intermédiaire</proficiency>
        </language>
        <language>
            <name>Kabyle</name>
            <proficiency>Bilingue ou natal (maternelle)</proficiency>
        </language>
        <language>
            <name>Arabe</name>
            <proficiency>Courant</proficiency>
        </language>
    </languages>
    <interests>
        <interest>Natation, musculation et basketball</interest>
        <interest>Jeux de stratégies</interest>
        <interest>Lecture</interest>
    </interests>
    <soft-skills>
        <skill>Rigoureux</skill>
        <skill>Sens des responsabilités</skill>
        <skill>Attentif aux détails</skill>
        <skill>Curieux</skill>
    </soft-skills>
    <technical-skills>
        <skill-category>
            <name>DevOps</name>
            <skills>
                <skill>Terraform</skill>
                <skill>Ansible</skill>
                <skill>Jenkins</skill>
                <skill>GitHub Actions</skill>
                <skill>XL Deploy</skill>
                <skill>Liquibase</skill>
            </skills>
        </skill-category>
        <skill-category>
            <name>Langages de programmation</name>
            <skills>
                <skill>C</skill>
                <skill>C++</skill>
                <skill>Java</skill>
                <skill>Python</skill>
                <skill>OCaml</skill>
                <skill>MatLab</skill>
            </skills>
        </skill-category>
        <skill-category>
            <name>Web</name>
            <skills>
                <skill>HTML &amp; CSS</skill>
                <skill>PHP</skill>
                <skill>JavaScript</skill>
            </skills>
        </skill-category>
        <skill-category>
            <name>Logiciels</name>
            <skills>
                <skill>Git</skill>
                <skill>Nginx</skill>
                <skill>Pack Office</skill>
                <skill>Eclipse</skill>
                <skill>Docker</skill>
            </skills>
        </skill-category>
        <skill-category>
            <name>Autres</name>
            <skills>
                <skill>UML</skill>
                <skill>SQL</skill>
                <skill>Apex Oracle</skill>
                <skill>Algorithmique (structures de données, algorithmique des graphes, programmation dynamique…)</skill>
            </skills>
        </skill-category>
    </technical-skills>
</cv>
